# -*- coding: utf-8 -*-
"""Hierarchical Inheritance (OOP)  0_0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H0RZcQ66PFkYe0gZHqJShQDmG3iUKvEk
"""

class Computer():
  def __init__(self, serial_number, manufacturer, model, processor, ram, display_size):
    self.serial_number = serial_number
    self.manufacturer = manufacturer
    self.model = model
    self.processor = processor
    self.ram = ram
    self.display_size = display_size

  def __str__(self):
    return f"Serial number: {self.serial_number}, Manufacturer: {self.manufacturer}, Model: {self.model}, Processor: {self.processor}, RAM: {self.ram} GB, Display: {self.display_size}\""


class Laptop(Computer):
  def __init__(self, serial_number, manufacturer, model, processor, ram, display_size, weight, is_touch_screen):
    super().__init__(serial_number, manufacturer, model, processor, ram, display_size)
    self.weight = weight
    self.is_touch_screen = is_touch_screen

  def print_info(self):
    print(str(self))
    print(f"Weight: {self.weight}lbs")
    print(f"Touch-Screen:{'True' if self.is_touch_screen else 'False'}")

class Desktop(Computer):
    def __init__(self, serial_number, manufacturer, model, processor, ram, display_size, type):
      super().__init__(serial_number,manufacturer,model,processor,ram,display_size)
      self.type = type

    def print_info(self):
      print(str(self))
      print(f"Type:{self.type}")

laptop = Laptop("A001", "Apple", "MacBook Air", "Apple M1",162, 13.3, 2.7, False)
print("Laptop info:")
laptop.print_info()

desktop = Desktop("A002", "Dell", "Inspiron", "core i7",32, 27,"All-in-one")
print("Desktop info:")
desktop.print_info()